In [2]:
import numpy as np
import matplotlib.pylab as plt

In [3]:
# Transpose
A = np.array([[11, 12, 13], [21, 22, 23]])
AT = A.T
print(A)
print(AT)

[[11 12 13]
 [21 22 23]]
[[11 21]
 [12 22]
 [13 23]]


In [4]:
# zero-vector
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [5]:
# ones-vector
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [6]:
# diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [7]:
# identity matrix
np.eye(4) # or np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
vx = np.array([[10], [11], [12]]) # vector x
vy = np.array([[1], [2], [3]]) # vector y
x = np.array([[10, 11], [20, 21]]) # matrix x
y = np.array([[1, 2], [3, 4]]) # matrix y

In [9]:
# matrix addition
print('vx + vy : \n', vx + vy)
print('x + y : \n', x + y)

vx + vy : 
 [[11]
 [13]
 [15]]
x + y : 
 [[11 13]
 [23 25]]


In [10]:
# broadcasting : addition between vector and scalar
vx + 10 # equals vx + (10 * np.ones((3, 1)))

array([[20],
       [21],
       [22]])

In [11]:
# dot product (벡터 내적)
vx.T @ vy

array([[68]])

In [10]:
# dot product with one dimension arrays (벡터 내적)
vx1 = np.array([[1], [2], [3]])
vy1 = np.array([[4], [5], [6]])

vx1.T @ vy1

array([[32]])

In [13]:
# weighted sum(가중평균)
w = np.array([[0.3], [0.7], [0.9], [0.2]])
x1 = np.array([[10], [100], [1000], [10000]])

w.T @ x1

array([[2973.]])

In [14]:
# 벡터의 평균
x2 = np.arange(10)
N = len(x2)

(np.ones(N) @ x2) / N

4.5

In [15]:
# 벡터의 평균
np.mean(x2)

4.5

In [16]:
# 평균제거(mean removed) 혹은 0-평균(zero-mean) 벡터
# : 벡터에서 벡터의 평균을 뺀 벡터
x3 = np.array([0, 1, 2, 3, 4])
N = len(x3)

x3 - ((np.ones(N).T @ x3 * np.ones(N)) / N)

array([-2., -1.,  0.,  1.,  2.])

In [17]:
x3 - np.mean(x3)

array([-2., -1.,  0.,  1.,  2.])

In [11]:
# 특정 행렬의 열의 평균으로 이루어진 벡터를 구한다

x5 = np.array([[3, 4, 5, 6], [3, 4, 5, 6], [3, 4, 5, 6]])
N = x5.shape[0]
mvector = (x5.T @ np.ones(N)) / N

mvector

array([3., 4., 5., 6.])

In [20]:
# 1N @ 1N.T

N = 3
one = np.array([[1], [1], [1]])

oneN = one @ one.T

oneN

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
# 위에있는 mvector(mvector in R(M))가 각 행으로 이루어진(mvector.T) 행렬 (Xbar in R(NxM))

x = np.array([[3, 4, 5, 6], [3, 4, 5, 6], [3, 4, 5, 6]])
one = np.array([[1], [1], [1]])
oneN = one @ one.T

Xbar = (oneN @ x) / 3

Xbar

array([[3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.]])

In [37]:
# vector matrix

v1 = np.array([[1], [2], [3]])
v2 = np.array([[4], [5], [6]])
v3 = np.array([[7], [8], [9]])

vectorMatrix = np.column_stack([v1, v2, v3])

vectorMatrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
# linear combination

w = np.array([[1], [2], [3]])

vectorMatrix @ w

array([[30],
       [36],
       [42]])

In [38]:
lambda1 = 0.5

vectorMatrix @ np.array([[lambda1], [0], [0]])

array([[0.5],
       [1. ],
       [1.5]])

In [45]:
# 여러 벡터에 대한 가중합 동시 계산

x1 = np.array([[1], [2], [3]])
x2 = np.array([[4], [5], [6]])
w = np.array([[0.2], [0.5], [0.8]])

np.vstack([x1.T, x2.T]) @ w

array([[3.6],
       [8.1]])