In [1]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
# Transpose
A = np.array([[11, 12, 13], [21, 22, 23]])
AT = A.T
print(A)
print(AT)

[[11 12 13]
 [21 22 23]]
[[11 21]
 [12 22]
 [13 23]]


In [3]:
# zero-vector
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [4]:
# ones-vector
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [5]:
# diagonal matrix
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
# identity matrix
np.eye(4) # or np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
vx = np.array([[10], [11], [12]]) # vector x
vy = np.array([[1], [2], [3]]) # vector y
x = np.array([[10, 11], [20, 21]]) # matrix x
y = np.array([[1, 2], [3, 4]]) # matrix y

In [8]:
# matrix addition
print('vx + vy : \n', vx + vy)
print('x + y : \n', x + y)

vx + vy : 
 [[11]
 [13]
 [15]]
x + y : 
 [[11 13]
 [23 25]]


In [9]:
# broadcasting : addition between vector and scalar
vx + 10 # equals vx + (10 * np.ones((3, 1)))

array([[20],
       [21],
       [22]])

In [10]:
# dot product (벡터 내적)
vx.T @ vy

array([[68]])

In [11]:
# dot product with one dimension arrays (벡터 내적)
vx1 = np.array([1, 2, 3])
vy1 = np.array([4, 5, 6])

vx1 @ vy1

32

In [12]:
# weighted sum(가중평균)
w = np.array([[0.3], [0.7], [0.9], [0.2]])
x1 = np.array([[10], [100], [1000], [10000]])

w.T @ x1

array([[2973.]])

In [13]:
# 벡터의 평균
x2 = np.arange(10)
N = len(x2)

(np.ones(N) @ x2) / N

4.5

In [14]:
# 벡터의 평균
np.mean(x2)

4.5

In [15]:
# 평균제거(mean removed) 혹은 0-평균(zero-mean) 벡터
# : 벡터에서 벡터의 평균을 뺀 벡터
x3 = np.array([0, 1, 2, 3, 4])
N = len(x3)

x3 - ((np.ones(N).T @ x3 * np.ones(N)) / N)

array([-2., -1.,  0.,  1.,  2.])

In [16]:
x3 - np.mean(x3)

array([-2., -1.,  0.,  1.,  2.])